import { useMemo, useRef, useState } from "react";
import type {
  LocationHistoryPlaceSummary,
  VisitedPlaceSummary
} from "../lib/historySummaryTypes";

type HistoryExplorerProps = {
  initialSummary?: LocationHistoryPlaceSummary | null;
};

export function HistoryExplorer({ initialSummary = null }: HistoryExplorerProps) {
  const [summary, setSummary] = useState<LocationHistoryPlaceSummary | null>(initialSummary);
  const [selectedPlace, setSelectedPlace] = useState<VisitedPlaceSummary | null>(null);
  const [message, setMessage] = useState("Import your private history summary JSON to explore visits.");
  const importInputRef = useRef<HTMLInputElement>(null);

  const groupedPlaces = useMemo(() => {
    const places = summary?.places ?? [];

    return {
      countries: places.filter((place) => place.scope === "country"),
      usStates: places.filter((place) => place.scope === "us-state"),
      indiaStates: places.filter((place) => place.scope === "india-state")
    };
  }, [summary]);

  async function importSummary(file: File | undefined) {
    if (!file) {
      return;
    }

    try {
      const parsed = JSON.parse(await file.text()) as LocationHistoryPlaceSummary;
      validateSummary(parsed);
      setSummary(parsed);
      setSelectedPlace(parsed.places[0] ?? null);
      setMessage(`Imported ${parsed.places.length} summarized places.`);
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Could not import that history summary.");
    } finally {
      if (importInputRef.current) {
        importInputRef.current.value = "";
      }
    }
  }

  return (
    <section className="history-page">
      <div className="history-header">
        <div>
          <p className="eyebrow">Location history</p>
          <h2>History Explorer</h2>
          <p className="lede">
            Import the private summary generated by `npm run summarize:history`. This page uses place
            summaries only, not raw coordinates.
          </p>
        </div>
        <div className="actions">
          <button type="button" onClick={() => importInputRef.current?.click()}>
            Import History JSON
          </button>
          <input
            ref={importInputRef}
            type="file"
            accept="application/json"
            className="visually-hidden"
            onChange={(event) => void importSummary(event.target.files?.[0])}
          />
        </div>
      </div>

      {summary ? (
        <div className="history-grid">
          <div className="history-summary-card">
            <span className="stats-value">{summary.places.length}</span>
            <span className="stats-label">places summarized</span>
            <p>{summary.sourcePointCount.toLocaleString()} private points processed locally.</p>
          </div>
          <PlaceGroup title="Countries" places={groupedPlaces.countries} onSelect={setSelectedPlace} />
          <PlaceGroup title="US States" places={groupedPlaces.usStates} onSelect={setSelectedPlace} />
          <PlaceGroup title="India States" places={groupedPlaces.indiaStates} onSelect={setSelectedPlace} />
          <PlaceDetails place={selectedPlace} />
        </div>
      ) : (
        <div className="empty-state">
          <p>{message}</p>
          <code>data/private/location-history-summary.json</code>
        </div>
      )}

      {summary ? (
        <p className="status-message" role="status">
          {message}
        </p>
      ) : null}
    </section>
  );
}

type PlaceGroupProps = {
  title: string;
  places: VisitedPlaceSummary[];
  onSelect: (place: VisitedPlaceSummary) => void;
};

function PlaceGroup({ title, places, onSelect }: PlaceGroupProps) {
  return (
    <section className="place-group">
      <h3>
        {title} <span>{places.length}</span>
      </h3>
      <div className="place-list">
        {places.slice(0, 24).map((place) => (
          <button className="place-row" type="button" key={place.key} onClick={() => onSelect(place)}>
            <span>{place.name}</span>
            <strong>{place.dayCount} days</strong>
          </button>
        ))}
      </div>
    </section>
  );
}

function PlaceDetails({ place }: { place: VisitedPlaceSummary | null }) {
  if (!place) {
    return (
      <section className="place-details">
        <h3>Select a place</h3>
        <p>Choose a country, US state, or India state to see visit date spans.</p>
      </section>
    );
  }

  return (
    <section className="place-details">
      <h3>{place.name}</h3>
      <p>
        {place.dayCount} unique days from {place.firstDate} to {place.lastDate}.
      </p>
      <div className="span-list">
        {place.dateSpans.slice(0, 40).map((span) => (
          <div className="span-row" key={`${place.key}-${span.startDate}-${span.endDate}`}>
            <span>
              {span.startDate}
              {span.endDate !== span.startDate ? ` → ${span.endDate}` : ""}
            </span>
            <strong>{span.dayCount} days</strong>
          </div>
        ))}
      </div>
    </section>
  );
}

function validateSummary(summary: LocationHistoryPlaceSummary) {
  if (summary.schemaVersion !== 1 || !Array.isArray(summary.places)) {
    throw new Error("Invalid history summary JSON");
  }
}
